# not separate zsh init because occurs parse error
# zsh
## prezto
## init before zplug because activate enhancd
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## zplug
export ZPLUG_HOME=~/.zplug
source $ZPLUG_HOME/init.zsh

zplug "b4b4r07/enhancd", use:init.sh
export ENHANCD_FILTER=peco
zplug "sindresorhus/pure"

if ! zplug check; then
    zplug install
fi

zplug load

# load zsh config files
ZSHHOME="${HOME}/.zsh.d"

for conf in "$ZSHHOME/"**/*.zsh; do
  source "${conf}"
done
unset conf


# pnpm
export PNPM_HOME="/home/ohira/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
