# not separate zsh init because occurs parse error
# zsh
## prezto
## init before zplug because activate enhancd
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## zplug
export ZPLUG_HOME=~/.zplug
source $ZPLUG_HOME/init.zsh

zplug "b4b4r07/enhancd", use:init.sh
export ENHANCD_FILTER=peco
zplug "sindresorhus/pure"

if ! zplug check; then
    zplug install
fi

zplug load

# load zsh config files
ZSHHOME="${HOME}/.zsh.d"

if [ -d $ZSHHOME ] && [ -r $ZSHHOME ] && [ -x $ZSHHOME ]; then
    for file in ${ZSHHOME}/**/*.zsh; do
        [ -r $file ] && source $file
    done
fi
